/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClefRouteImport } from './routes/clef'
import { Route as ApiClefRouteImport } from './routes/api/clef'
import { Route as ApiExtractRouteImport } from './routes/api/extract'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiJobsIdRouteImport } from './routes/api/jobs/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClefRoute = ClefRouteImport.update({
  id: '/clef',
  path: '/clef',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClefRoute = ApiClefRouteImport.update({
  id: '/api/clef',
  path: '/api/clef',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtractRoute = ApiExtractRouteImport.update({
  id: '/api/extract',
  path: '/api/extract',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsIdRoute = ApiJobsIdRouteImport.update({
  id: '/api/jobs/$id',
  path: '/api/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clef': typeof ClefRoute
  '/api/clef': typeof ApiClefRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/jobs/$id': typeof ApiJobsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clef': typeof ClefRoute
  '/api/clef': typeof ApiClefRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/jobs/$id': typeof ApiJobsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clef': typeof ClefRoute
  '/api/clef': typeof ApiClefRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/jobs/$id': typeof ApiJobsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/clef' | '/api/clef' | '/api/extract' | '/api/mcp' | '/api/jobs/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/clef' | '/api/clef' | '/api/extract' | '/api/mcp' | '/api/jobs/$id'
  id:
    | '__root__'
    | '/'
    | '/clef'
    | '/api/clef'
    | '/api/extract'
    | '/api/mcp'
    | '/api/jobs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClefRoute: typeof ClefRoute
  ApiClefRoute: typeof ApiClefRoute
  ApiExtractRoute: typeof ApiExtractRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiJobsIdRoute: typeof ApiJobsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clef': {
      id: '/clef'
      path: '/clef'
      fullPath: '/clef'
      preLoaderRoute: typeof ClefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clef': {
      id: '/api/clef'
      path: '/api/clef'
      fullPath: '/api/clef'
      preLoaderRoute: typeof ApiClefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extract': {
      id: '/api/extract'
      path: '/api/extract'
      fullPath: '/api/extract'
      preLoaderRoute: typeof ApiExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/$id': {
      id: '/api/jobs/$id'
      path: '/api/jobs/$id'
      fullPath: '/api/jobs/$id'
      preLoaderRoute: typeof ApiJobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClefRoute: ClefRoute,
  ApiClefRoute: ApiClefRoute,
  ApiExtractRoute: ApiExtractRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiJobsIdRoute: ApiJobsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
